-- PROD etl_prod, 2026-09-03: регистр order (Документ.ЗаказПокупателя, _Document271) в чистой модели.
-- Часть 1: DDL orders / order_positions. Часть 2: etl_meta (pipeline_type document_with_vt, retail orders.document_uid).
-- Применено на etl_prod 2026-09-03; см. docs/knowledge/decisions/Регистр order строится от шапки документа….md

-- ======================= Часть 1: DDL =======================
-- PROD etl_prod: регистр order (Документ.ЗаказПокупателя, _Document271). Чистая модель по эталону sales.
-- Имя шапки — orders: слово order зарезервировано в SQL, а движок пишет public.{table} без кавычек.
BEGIN;

CREATE TABLE public.orders (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- технические ключи (upsert, tail, missing-delete, сверка)
    recorder               uuid        NOT NULL,          -- _Document271._IDRRef
    recorder_type          integer     NOT NULL,          -- 271, константа пайплайна
    period                 timestamp   NOT NULL,          -- _Date_Time (fix_year)
    doc_number             varchar(255),                  -- _Number
    -- DIM refs (BIGINT, резолв в post_load из raw_refs)
    kontragent_id          bigint,                        -- Контрагент      _Fld4689RRef → dim_kontragent
    dogovor_id             bigint,                        -- ДоговорКонтрагента _Fld4682RRef → dim_dogovor
    organizatsiya_id       bigint,                        -- Организация     _Fld4694RRef → dim_organizatsiya
    otvetstvennyy_id       bigint,                        -- Ответственный   _Fld4695RRef → dim_otvetstvennyy
    podrazdelenie_id       bigint,                        -- Подразделение   _Fld4697RRef → dim_podrazdelenie
    sklad_id               bigint,                        -- СкладГруппа     _Fld4699_RRRef (только тип 169) → dim_sklad
    gruzopoluchatel_id     bigint,                        -- Грузополучатель _Fld4677RRef → dim_kontragent
    -- меры / атрибуты
    summa_documenta        numeric(18,4),                 -- СуммаДокумента        _Fld4703
    kolichestvo_tovara     numeric(18,4),                 -- КоличестоТовара       _Fld19949
    evrika_summa_bonusami  numeric(18,4),                 -- ЭВРИКА_СуммаБонусами  _Fld24261
    akciya_bonus           numeric(18,4),                 -- АкцияБонус            _Fld22958
    nomer_internet_zakaza  varchar(60),                   -- НомерИнтернетЗаказа   _Fld23063
    -- исходные ссылки 1С (стандарт raw_refs)
    raw_refs               jsonb,
    -- ETL audit (как в sales)
    etl_loaded_at          timestamp DEFAULT now(),
    etl_updated_at         timestamp,
    retail_snapshot_at     timestamp,
    retail_updated_at      timestamp,
    CONSTRAINT orders_recorder_recorder_type_key UNIQUE (recorder, recorder_type)
);
CREATE INDEX idx_orders_period             ON public.orders (period);
CREATE INDEX idx_orders_kontragent_id      ON public.orders (kontragent_id);
CREATE INDEX idx_orders_dogovor_id         ON public.orders (dogovor_id);
CREATE INDEX idx_orders_otvetstvennyy_id   ON public.orders (otvetstvennyy_id);
CREATE INDEX idx_orders_podrazdelenie_id   ON public.orders (podrazdelenie_id);
CREATE INDEX idx_orders_sklad_id           ON public.orders (sklad_id);
CREATE INDEX idx_orders_gruzopoluchatel_id ON public.orders (gruzopoluchatel_id);
CREATE INDEX idx_orders_raw_refs_gin       ON public.orders USING gin (raw_refs);
CREATE INDEX idx_orders_retail_snapshot_at ON public.orders (retail_snapshot_at) WHERE retail_snapshot_at IS NOT NULL;
CREATE INDEX idx_orders_retail_updated_at  ON public.orders (retail_updated_at)  WHERE retail_updated_at  IS NOT NULL;

CREATE TABLE public.order_positions (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               bigint,                        -- → orders.id (post_load по recorder+recorder_type)
    -- технические ключи
    recorder               uuid        NOT NULL,          -- _Document271_IDRRef
    recorder_type          integer     NOT NULL,          -- 271
    vt_kind                varchar(10) NOT NULL,          -- 'product' (_VT4708 Товары) | 'service' (_VT4746 Услуги)
    line_no                integer     NOT NULL,          -- _LineNo4709 | _LineNo4747
    -- DIM refs
    nomenklatura_id        bigint,                        -- _Fld4714RRef | _Fld4754RRef → dim_nomenklatura
    kachestvo_id           bigint,                        -- _Fld24518RRef (только товары) → dim_kachestvo
    otvetstvennyy_id       bigint,                        -- _Fld24668RRef | _Fld24669RRef → dim_otvetstvennyy
    sklad_id               bigint,                        -- СкладОтгрузки _Fld24721RRef (только товары) → dim_sklad
    -- меры
    kolichestvo            numeric(18,4),                 -- _Fld4711 | _Fld4749
    tsena                  numeric(18,4),                 -- _Fld4724 | _Fld4750
    summa                  numeric(18,4),                 -- _Fld4720 | _Fld4751
    nds                    numeric(18,4),                 -- _Fld4721 | _Fld4753
    skidka_pct             numeric(18,4),                 -- ПроцентСкидкиНаценки _Fld4716 | _Fld4755
    podarochnaya_skidka    numeric(18,4),                 -- ПодарочнаяСкидка _Fld19986 (только товары)
    evrika_bonusy          numeric(18,4),                 -- _Fld26962 (только товары; подтверждено по sales)
    evrika_spisannye       numeric(18,4),                 -- _Fld26963 (только товары; подтверждено по sales)
    raw_refs               jsonb,
    etl_loaded_at          timestamp DEFAULT now(),
    etl_updated_at         timestamp,
    retail_snapshot_at     timestamp,
    retail_updated_at      timestamp,
    CONSTRAINT order_positions_nk_key UNIQUE (recorder, recorder_type, vt_kind, line_no)
);
CREATE INDEX idx_order_positions_order_id        ON public.order_positions (order_id);
CREATE INDEX idx_order_positions_nomenklatura_id ON public.order_positions (nomenklatura_id);
CREATE INDEX idx_order_positions_sklad_id        ON public.order_positions (sklad_id);
CREATE INDEX idx_order_positions_etl_updated_at  ON public.order_positions (etl_updated_at);

COMMIT;

-- ======================= Часть 2: etl_meta =======================
-- PROD etl_prod: metadata регистра order. Источник — UPP_JAN (все колонки проверены по INFORMATION_SCHEMA и по данным).
-- Пайплайн: document_with_vt — шапка (source) + UNION ALL двух ТЧ (union), generic-путь QueryBuilder.
BEGIN;

WITH reg AS (
  INSERT INTO etl_meta.registers (code, name, description, default_mode, pipeline_type, retail_table, retail_uid_column, is_active)
  VALUES ('order', 'Заказы покупателей', 'Документ.ЗаказПокупателя (_Document271): шапка → orders, ТЧ Товары+Услуги → order_positions',
          'full_period', 'document_with_vt', 'orders', 'document_uid', true)
  RETURNING id
),
hdr AS (
  INSERT INTO etl_meta.register_sources (register_id, source_code, source_type, mssql_schema, mssql_table, where_clause, priority, is_active, onec_name, period_column)
  SELECT id, 'doc_271', 'header', 'dbo', '_Document271',
         '[{alias}].[_Posted] = 0x01 AND [{alias}].[_Marked] = 0x00', 0, true, 'Документ.ЗаказПокупателя', '_Date_Time' FROM reg
  RETURNING id, register_id
),
vt_g AS (
  INSERT INTO etl_meta.register_sources (register_id, source_code, source_type, mssql_schema, mssql_table, parent_source_id, join_type, join_key_source, join_key_parent, priority, is_active, onec_name, period_column)
  SELECT register_id, 'doc_271_vt_4708', 'detail', 'dbo', '_Document271_VT4708', id, 'INNER', '_Document271_IDRRef', '_IDRRef', 1, true, 'Документ.ЗаказПокупателя.Товары', '' FROM hdr
  RETURNING id, register_id
),
vt_s AS (
  INSERT INTO etl_meta.register_sources (register_id, source_code, source_type, mssql_schema, mssql_table, parent_source_id, join_type, join_key_source, join_key_parent, priority, is_active, onec_name, period_column)
  SELECT h.register_id, 'doc_271_vt_4746', 'detail', 'dbo', '_Document271_VT4746', h.id, 'INNER', '_Document271_IDRRef', '_IDRRef', 2, true, 'Документ.ЗаказПокупателя.Услуги', '' FROM hdr h
  RETURNING id, register_id
),
un AS (
  INSERT INTO etl_meta.source_unions (register_id, union_code, description, output_columns, is_active)
  SELECT register_id, 'order_positions_u', 'Товары ∪ Услуги заказа',
         ARRAY['recorder','recorder_type','line_no','vt_kind','kolichestvo','tsena','summa','nds','skidka_pct','podarochnaya_skidka',
               'evrika_bonusy','evrika_spisannye','raw_refs.nomenklatura','raw_refs.kachestvo','raw_refs.otvetstvennyy','raw_refs.sklad','raw_refs.stavka_nds'], true
  FROM hdr RETURNING id
),
unm AS (
  INSERT INTO etl_meta.source_union_members (union_id, source_id, priority, is_active)
  SELECT un.id, vt_g.id, 1, true FROM un, vt_g UNION ALL SELECT un.id, vt_s.id, 2, true FROM un, vt_s
  RETURNING id
),
t_hdr AS (
  INSERT INTO etl_meta.register_targets (register_id, target_schema, target_table, source_id, load_mode, upsert_keys, include_columns, priority, target_role, is_active, post_load_sql)
  SELECT register_id, 'public', 'orders', id, 'upsert', ARRAY['recorder','recorder_type'],
         ARRAY['period','recorder','recorder_type','doc_number','summa_documenta','kolichestvo_tovara','evrika_summa_bonusami','akciya_bonus','nomer_internet_zakaza',
               'raw_refs.kontragent','raw_refs.dogovor','raw_refs.organizatsiya','raw_refs.otvetstvennyy','raw_refs.podrazdelenie','raw_refs.sklad','raw_refs.gruzopoluchatel',
               'raw_refs.vid_operatsii','raw_refs.tip_cen','raw_refs.diskontnaya_karta','raw_refs.avtor','raw_refs.evrika_tip_zakaza','raw_refs.sposob_dostavki','raw_refs.pol_klienta',
               'raw_refs.klient.type','raw_refs.klient.uid','raw_refs.strukturnaya_edinitsa.type','raw_refs.strukturnaya_edinitsa.uid','raw_refs'],
         0, 'dimension', true,
$PL$
-- Стандарт ссылок: исходные GUID только в raw_refs; *_id — stub + резолв dim.guid → dim.id. Пустая ссылка 1С в raw_refs не пишется.
INSERT INTO public.dim_kontragent (guid) SELECT DISTINCT (raw_refs->>'kontragent')::uuid FROM public.orders WHERE kontragent_id IS NULL AND raw_refs ? 'kontragent' ON CONFLICT (guid) DO NOTHING;
UPDATE public.orders o SET kontragent_id = d.id FROM public.dim_kontragent d WHERE o.kontragent_id IS NULL AND d.guid = (o.raw_refs->>'kontragent')::uuid;
INSERT INTO public.dim_dogovor (guid) SELECT DISTINCT (raw_refs->>'dogovor')::uuid FROM public.orders WHERE dogovor_id IS NULL AND raw_refs ? 'dogovor' ON CONFLICT (guid) DO NOTHING;
UPDATE public.orders o SET dogovor_id = d.id FROM public.dim_dogovor d WHERE o.dogovor_id IS NULL AND d.guid = (o.raw_refs->>'dogovor')::uuid;
INSERT INTO public.dim_organizatsiya (guid) SELECT DISTINCT (raw_refs->>'organizatsiya')::uuid FROM public.orders WHERE organizatsiya_id IS NULL AND raw_refs ? 'organizatsiya' ON CONFLICT (guid) DO NOTHING;
UPDATE public.orders o SET organizatsiya_id = d.id FROM public.dim_organizatsiya d WHERE o.organizatsiya_id IS NULL AND d.guid = (o.raw_refs->>'organizatsiya')::uuid;
INSERT INTO public.dim_otvetstvennyy (guid) SELECT DISTINCT (raw_refs->>'otvetstvennyy')::uuid FROM public.orders WHERE otvetstvennyy_id IS NULL AND raw_refs ? 'otvetstvennyy' ON CONFLICT (guid) DO NOTHING;
UPDATE public.orders o SET otvetstvennyy_id = d.id FROM public.dim_otvetstvennyy d WHERE o.otvetstvennyy_id IS NULL AND d.guid = (o.raw_refs->>'otvetstvennyy')::uuid;
INSERT INTO public.dim_podrazdelenie (guid) SELECT DISTINCT (raw_refs->>'podrazdelenie')::uuid FROM public.orders WHERE podrazdelenie_id IS NULL AND raw_refs ? 'podrazdelenie' ON CONFLICT (guid) DO NOTHING;
UPDATE public.orders o SET podrazdelenie_id = d.id FROM public.dim_podrazdelenie d WHERE o.podrazdelenie_id IS NULL AND d.guid = (o.raw_refs->>'podrazdelenie')::uuid;
INSERT INTO public.dim_sklad (guid) SELECT DISTINCT (raw_refs->>'sklad')::uuid FROM public.orders WHERE sklad_id IS NULL AND raw_refs ? 'sklad' ON CONFLICT (guid) DO NOTHING;
UPDATE public.orders o SET sklad_id = d.id FROM public.dim_sklad d WHERE o.sklad_id IS NULL AND d.guid = (o.raw_refs->>'sklad')::uuid;
-- Грузополучатель — тот же справочник Контрагенты
INSERT INTO public.dim_kontragent (guid) SELECT DISTINCT (raw_refs->>'gruzopoluchatel')::uuid FROM public.orders WHERE gruzopoluchatel_id IS NULL AND raw_refs ? 'gruzopoluchatel' ON CONFLICT (guid) DO NOTHING;
UPDATE public.orders o SET gruzopoluchatel_id = d.id FROM public.dim_kontragent d WHERE o.gruzopoluchatel_id IS NULL AND d.guid = (o.raw_refs->>'gruzopoluchatel')::uuid;
-- Этап 12 (включается после ALTER TABLE public.sales ADD COLUMN zakaz_id bigint):
-- UPDATE public.sales s SET zakaz_id = o.id FROM public.orders o
-- WHERE s.zakaz_id IS NULL AND o.etl_updated_at >= timezone('Asia/Almaty', now()) - interval '60 minutes'
--   AND s.raw_refs @> jsonb_build_object('zakaz', jsonb_build_object('type', 271, 'uid', o.recorder::text));
$PL$
  FROM hdr RETURNING id, register_id
),
t_pos AS (
  INSERT INTO etl_meta.register_targets (register_id, target_schema, target_table, union_id, load_mode, upsert_keys, include_columns, priority, target_role, is_active, parent_target_id, post_load_sql)
  SELECT t.register_id, 'public', 'order_positions', un.id, 'upsert', ARRAY['recorder','recorder_type','vt_kind','line_no'],
         ARRAY['recorder','recorder_type','vt_kind','line_no','kolichestvo','tsena','summa','nds','skidka_pct','podarochnaya_skidka','evrika_bonusy','evrika_spisannye',
               'raw_refs.nomenklatura','raw_refs.kachestvo','raw_refs.otvetstvennyy','raw_refs.sklad','raw_refs.stavka_nds','raw_refs'],
         1, 'fact', true, t.id,
$PL$
-- FK на шапку по natural key
UPDATE public.order_positions p SET order_id = o.id FROM public.orders o
WHERE p.recorder = o.recorder AND p.recorder_type = o.recorder_type AND p.order_id IS NULL;
-- Справочники: stub + резолв из raw_refs
INSERT INTO public.dim_nomenklatura (guid) SELECT DISTINCT (raw_refs->>'nomenklatura')::uuid FROM public.order_positions WHERE nomenklatura_id IS NULL AND raw_refs ? 'nomenklatura' ON CONFLICT (guid) DO NOTHING;
UPDATE public.order_positions p SET nomenklatura_id = d.id FROM public.dim_nomenklatura d WHERE p.nomenklatura_id IS NULL AND d.guid = (p.raw_refs->>'nomenklatura')::uuid;
INSERT INTO public.dim_kachestvo (guid) SELECT DISTINCT (raw_refs->>'kachestvo')::uuid FROM public.order_positions WHERE kachestvo_id IS NULL AND raw_refs ? 'kachestvo' ON CONFLICT (guid) DO NOTHING;
UPDATE public.order_positions p SET kachestvo_id = d.id FROM public.dim_kachestvo d WHERE p.kachestvo_id IS NULL AND d.guid = (p.raw_refs->>'kachestvo')::uuid;
INSERT INTO public.dim_otvetstvennyy (guid) SELECT DISTINCT (raw_refs->>'otvetstvennyy')::uuid FROM public.order_positions WHERE otvetstvennyy_id IS NULL AND raw_refs ? 'otvetstvennyy' ON CONFLICT (guid) DO NOTHING;
UPDATE public.order_positions p SET otvetstvennyy_id = d.id FROM public.dim_otvetstvennyy d WHERE p.otvetstvennyy_id IS NULL AND d.guid = (p.raw_refs->>'otvetstvennyy')::uuid;
INSERT INTO public.dim_sklad (guid) SELECT DISTINCT (raw_refs->>'sklad')::uuid FROM public.order_positions WHERE sklad_id IS NULL AND raw_refs ? 'sklad' ON CONFLICT (guid) DO NOTHING;
UPDATE public.order_positions p SET sklad_id = d.id FROM public.dim_sklad d WHERE p.sklad_id IS NULL AND d.guid = (p.raw_refs->>'sklad')::uuid;
-- Строки, исчезнувшие из документа при перепроведении (тот же приём, что в sales_positions: окно 60 мин, зазор 30 мин)
DELETE FROM public.order_positions p
USING (SELECT recorder, recorder_type, MAX(etl_updated_at) AS last_ts FROM public.order_positions
       WHERE etl_updated_at >= timezone('Asia/Almaty', now()) - interval '60 minutes' GROUP BY recorder, recorder_type) m
WHERE p.recorder = m.recorder AND p.recorder_type = m.recorder_type AND p.etl_updated_at < m.last_ts - interval '30 minutes';
$PL$
  FROM t_hdr t, un RETURNING id, register_id
),
m_hdr AS (
  INSERT INTO etl_meta.column_mappings (source_id, source_column, target_column, is_expression, transform_type, target_type, is_active, register_id, target_id, onec_name)
  SELECT h.id, m.src, m.tgt, m.expr, m.tr, m.ty, true, h.register_id, t.id, m.nm FROM hdr h, t_hdr t, (VALUES
    ('_IDRRef',        'recorder',              false, 'binary_to_uuid', 'uuid',      'Ссылка'),
    ('CAST(271 AS int)','recorder_type',        true,  NULL,             'integer',   'тип документа (константа 271)'),
    ('_Date_Time',     'period',                false, 'fix_year',       'timestamp', 'Дата'),
    ('_Number',        'doc_number',            false, NULL,             'text',      'Номер'),
    ('_Fld4703',       'summa_documenta',       false, NULL,             'numeric',   'СуммаДокумента'),
    ('_Fld19949',      'kolichestvo_tovara',    false, NULL,             'numeric',   'КоличестоТовара'),
    ('_Fld24261',      'evrika_summa_bonusami', false, NULL,             'numeric',   'ЭВРИКА_СуммаБонусами'),
    ('_Fld22958',      'akciya_bonus',          false, NULL,             'numeric',   'АкцияБонус'),
    ('_Fld23063',      'nomer_internet_zakaza', false, NULL,             'text',      'НомерИнтернетЗаказа'),
    ('_Fld4689RRef',   'raw_refs.kontragent',   false, 'binary_to_uuid', 'uuid',      'Контрагент'),
    ('_Fld4682RRef',   'raw_refs.dogovor',      false, 'binary_to_uuid', 'uuid',      'ДоговорКонтрагента'),
    ('_Fld4694RRef',   'raw_refs.organizatsiya',false, 'binary_to_uuid', 'uuid',      'Организация'),
    ('_Fld4695RRef',   'raw_refs.otvetstvennyy',false, 'binary_to_uuid', 'uuid',      'Ответственный'),
    ('_Fld4697RRef',   'raw_refs.podrazdelenie',false, 'binary_to_uuid', 'uuid',      'Подразделение'),
    ('CASE WHEN [{alias}].[_Fld4699_RTRef] = 0x000000A9 THEN [{alias}].[_Fld4699_RRRef] END', 'raw_refs.sklad', true, 'binary_to_uuid', 'uuid', 'СкладГруппа (только Справочник.Склады, тип 169)'),
    ('_Fld4677RRef',   'raw_refs.gruzopoluchatel', false, 'binary_to_uuid', 'uuid',   'Грузополучатель'),
    ('_Fld4675RRef',   'raw_refs.vid_operatsii',  false, 'binary_to_uuid', 'uuid',    'ВидОперации (Enum557)'),
    ('_Fld4704RRef',   'raw_refs.tip_cen',        false, 'binary_to_uuid', 'uuid',    'ТипЦен (Reference206)'),
    ('_Fld4681RRef',   'raw_refs.diskontnaya_karta', false, 'binary_to_uuid', 'uuid', 'ДисконтнаяКарта (Reference87 ИнформационныеКарты)'),
    ('_Fld4672RRef',   'raw_refs.avtor',          false, 'binary_to_uuid', 'uuid',    'Автор'),
    ('_Fld22871RRef',  'raw_refs.evrika_tip_zakaza', false, 'binary_to_uuid', 'uuid', 'Эврика_ТипЗаказа (Enum22868)'),
    ('_Fld22873RRef',  'raw_refs.sposob_dostavki', false, 'binary_to_uuid', 'uuid',   'Эврика_СпособДоставки (Enum22870)'),
    ('_Fld25267RRef',  'raw_refs.pol_klienta',    false, 'binary_to_uuid', 'uuid',    'ПолКлиента (Enum715 ПолФизическихЛиц)'),
    ('_Fld24454_RTRef','raw_refs.klient.type',    false, 'binary_to_int',  'integer', 'Клиент — тип (Reference28021)'),
    ('_Fld24454_RRRef','raw_refs.klient.uid',     false, 'binary_to_uuid', 'uuid',    'Клиент — uid'),
    ('_Fld4700_RTRef', 'raw_refs.strukturnaya_edinitsa.type', false, 'binary_to_int', 'integer', 'СтруктурнаяЕдиница — тип'),
    ('_Fld4700_RRRef', 'raw_refs.strukturnaya_edinitsa.uid',  false, 'binary_to_uuid', 'uuid',  'СтруктурнаяЕдиница — uid')
  ) AS m(src, tgt, expr, tr, ty, nm)
  RETURNING id
),
m_g AS (
  INSERT INTO etl_meta.column_mappings (source_id, source_column, target_column, is_expression, transform_type, target_type, is_active, register_id, target_id, onec_name)
  SELECT v.id, m.src, m.tgt, m.expr, m.tr, m.ty, true, v.register_id, t.id, m.nm FROM vt_g v, t_pos t, (VALUES
    ('_LineNo4709',  'line_no',              false, NULL, 'integer', 'НомерСтроки'),
    ('''product''',  'vt_kind',              true,  NULL, 'text',    'вид ТЧ: Товары'),
    ('_Fld4711',     'kolichestvo',          false, NULL, 'numeric', 'Количество'),
    ('_Fld4724',     'tsena',                false, NULL, 'numeric', 'Цена'),
    ('_Fld4720',     'summa',                false, NULL, 'numeric', 'Сумма'),
    ('_Fld4721',     'nds',                  false, NULL, 'numeric', 'СуммаНДС'),
    ('_Fld4716',     'skidka_pct',           false, NULL, 'numeric', 'ПроцентСкидкиНаценки'),
    ('_Fld19986',    'podarochnaya_skidka',  false, NULL, 'numeric', 'ПодарочнаяСкидка'),
    ('_Fld26962',    'evrika_bonusy',        false, NULL, 'numeric', 'Эврика_Бонусы (подтверждено по sales)'),
    ('_Fld26963',    'evrika_spisannye',     false, NULL, 'numeric', 'Эврика_Списанные (подтверждено по sales)'),
    ('_Fld4714RRef', 'raw_refs.nomenklatura',false, 'binary_to_uuid', 'uuid', 'Номенклатура'),
    ('_Fld24518RRef','raw_refs.kachestvo',   false, 'binary_to_uuid', 'uuid', 'Качество (по данным: Reference97)'),
    ('_Fld24668RRef','raw_refs.otvetstvennyy',false,'binary_to_uuid', 'uuid', 'Ответственный (по данным: Reference145)'),
    ('_Fld24721RRef','raw_refs.sklad',       false, 'binary_to_uuid', 'uuid', 'СкладОтгрузки (по данным: Reference169)'),
    ('_Fld4719RRef', 'raw_refs.stavka_nds',  false, 'binary_to_uuid', 'uuid', 'СтавкаНДС')
  ) AS m(src, tgt, expr, tr, ty, nm)
  RETURNING id
),
m_s AS (
  INSERT INTO etl_meta.column_mappings (source_id, source_column, target_column, is_expression, transform_type, target_type, is_active, register_id, target_id, onec_name)
  SELECT v.id, m.src, m.tgt, m.expr, m.tr, m.ty, true, v.register_id, t.id, m.nm FROM vt_s v, t_pos t, (VALUES
    ('_LineNo4747',  'line_no',              false, NULL, 'integer', 'НомерСтроки'),
    ('''service''',  'vt_kind',              true,  NULL, 'text',    'вид ТЧ: Услуги'),
    ('_Fld4749',     'kolichestvo',          false, NULL, 'numeric', 'Количество'),
    ('_Fld4750',     'tsena',                false, NULL, 'numeric', 'Цена'),
    ('_Fld4751',     'summa',                false, NULL, 'numeric', 'Сумма'),
    ('_Fld4753',     'nds',                  false, NULL, 'numeric', 'СуммаНДС'),
    ('_Fld4755',     'skidka_pct',           false, NULL, 'numeric', 'ПроцентСкидкиНаценки'),
    ('_Fld4754RRef', 'raw_refs.nomenklatura',false, 'binary_to_uuid', 'uuid', 'Номенклатура'),
    ('_Fld24669RRef','raw_refs.otvetstvennyy',false,'binary_to_uuid', 'uuid', 'Ответственный (по данным: Reference145)'),
    ('_Fld4752RRef', 'raw_refs.stavka_nds',  false, 'binary_to_uuid', 'uuid', 'СтавкаНДС'),
    ('CAST(NULL AS binary(16))', 'raw_refs.sklad', true, NULL, 'uuid', 'у услуг нет СкладОтгрузки — явный NULL, иначе union наследует СкладГруппа шапки')
  ) AS m(src, tgt, expr, tr, ty, nm)
  RETURNING id
)
SELECT (SELECT count(*) FROM m_hdr) hdr_mappings, (SELECT count(*) FROM m_g) goods_mappings, (SELECT count(*) FROM m_s) service_mappings, (SELECT count(*) FROM unm) union_members;

COMMIT;
